### PR TITLE
fix: php 8.2 deprecated

### LINKED ISSUE #72: PHP Warnings running under PHP 8.2
```
PHP Deprecated:  Creation of dynamic property HM\Cavalcade\Runner\Logger::$db is deprecated in /etc/cavalcade/inc/class-logger.php on line 8
PHP Deprecated:  Creation of dynamic property HM\Cavalcade\Runner\Logger::$table_prefix is deprecated in /etc/cavalcade/inc/class-logger.php on line 9
PHP Deprecated:  Creation of dynamic property HM\Cavalcade\Runner\Job::$schedule is deprecated in /etc/cavalcade/inc/class-runner.php on line 251
```

### PR DESCRIPTION
**Pull request by devhaozi**
Close #72

### CODE REVIEW

File: inc/class-logger.php [hunk 1]
```diff
@@ -3,6 +3,11 @@
 namespace HM\Cavalcade\Runner;
 
 class Logger {
+	protected $db;
+	protected $table_prefix;
+
+	protected $db;
+	protected $table_prefix;
```
Comment (rmccue) [inline inc/class-logger.php:10]: These seem to be accidentally duplicated?

```suggestion
```

**Review by rmccue — CHANGES_REQUESTED** [review]

**Comment by devhaozi** [comment]
@rmccue Could you help to review this pr?

**Review by mikelittle — APPROVED** [review]
Looks good now. Thanks for this.
